### ISSUE TITLE
Description Interface: Must all profiles be returned?

### ISSUE THREAD

**Issue by otto-ifak** [admin-shell-io/aas-specs-api#328]
Assuming a server implements `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001`.

Must `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002` be returned for `/description` or is this implicitly assumed?

**Comment by sebbader-sap** [comment]
It is recommended to have _all_ supported profiles in the list, however, it shall not be enforced. Therefore, a test engine must not fail the test for a profile like AssetAdministrationShellRepositoryServiceSpecification/SSP-002 if only `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001` is exposed in the profiles array.

**Comment by mjacoby** [comment]
This is inconsistent. If using the above stated approach that it is only recommended but not required to explicitly send all supported profiles and there also is no explicitly defined hierarchy of the profiles, then this functionality shall **not** be tested at all because it is not well-defined.

So we have the following options

1. all supported profiles must be listed explicitly, following in...
  - test must be implemented and expect exact match
  - somewhat breaking changes as existing implementations of a server would no longer be compliant (however, we typically consider breaking changes only from client perspective)
2. profiles have a fixed hierarchy explicitly defined in the specification, they may also be explicitly be listed, following in
  - test must be implemented and expect exact match or match of any "super"-profiles in the hierarchy
  - probably breaking changes from client perspective, as now clients have to know about the hierarchy and understand/interpret it
3. it is only recommended to explicitly list all supported profiles and there is no explicitly defined hierarchy of profiles, following in...
  - no test can be implemented as the behavior is not well-defined
  - no breaking changes from any perspective
  - `/description ` becomes/stays useless as meaning is unclear

  
One could argue that there is a hierarchy of profiles implicitly defined in the specification through the definitions of the profiles themselves. This is basically what @sebbader-sap described by the above posts. Although this is technically correct, I would not consider this an adequate solution because not explicitly defining this hierarchy means that every reader must deduct this hierarchy for themselves which is very cumbersome and also error-prone as the profiles can become quite complex. I therefore argue that this should therefore be avoided at all costs. In this case, there would not be any breaking changes in making this implicit information explicit, i.e. adding an explicit hierarchy of profiles.

Personally, I vote for option 1 as it is the most simplest to implement for server and client and is easy to understand. Also, as mentioned, API breaking changes are typically only considered from user perspective which would not require a breaking change. In fact, I would say I doesn't even require an increase of the minor version as it is more of a bugfix clarifying undefined behavior.

**Comment by sebbader-sap** [comment]
@BirgitBoss @arnoweiss can you add some context what already existing ecosystems (Catena-X) require? In particular, is it enforced that a DT Registry has 
1. both `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001` (full) and `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002` (read)
2. At least `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002` (read) but may have `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001` (full) as well
3. only `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001` (full) is sufficient as the `https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002` (read) is included?

**Comment by BirgitBoss** [comment]
In [CX-0002](https://catenax-ev.github.io/docs/next/standards/CX-0002-DigitalTwinsInCatenaX#212-api-endpoints--resources)  the following example is given:

```
{
  "profiles": [
    "https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001",
    "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002"
   ]
}
```

In [Digital Twin KIT ](https://eclipse-tractusx.github.io/docs-kits/kits/Digital%20Twin%20Kit/Software%20Development%20View/dt-kit-software-development-view) it seems no example is given.

Probably no application so far is using the GetSelfDescription API.

**Comment by BirgitBoss** [comment]
@tunacicek how are we recommending to fill the information when using the Tractus-X DTR?

**Comment by waltersve** [comment]
@BirgitBoss it is a fixed list which can't be customized describing which precise profiles are supported in the a corresponding version of the [OSS registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/5fd15e8f136bba79f1dd55ed12a54de872acfccd/backend/src/main/java/org/eclipse/tractusx/semantics/registry/controller/AssetAdministrationShellApiDelegate.java#L80).

**Comment by BirgitBoss** [comment]
So from Catena we cannot learn. So either
- we define a clear hierarchy in the IDTA 01002 or
- we require to add all profiles supported even if some profiles are included in others.

**Comment by sebbader-sap** [comment]
Following our discussion, I personally come to the following conclusion:

Option #1 is correct: ...all supported profiles must be listed explicitly...
with these implications for real-world implementations:
1. If an AAS server wants to to get certified against the "Full Profile", it has to provide the "Full Profile", the "Read Profile", and any other profile that comes with future AAS versions as long as these profiles are part of the supported AAS major+minor version. A test framework needs to check this.
2. If an AAS server wants to to get certified against the "Read Profile", or any comparable future profile, but by chance also supports a more comprehensive profile like the "Full Profile", it must expose the "Read Profile" in the list but may also have the "Full Profile" listed. A test framework needs to check the existence of the "Read Profile" declaration and ignore the other ones. This leaves the question open how a client might check the certification state of a server.
3. Why not prohibiting the "Full Profile" in case 2, as the certification body did not verify it's correctness? I can expect that vendor's also want to expose own profiles on top of the AAS-defined ones. In any such case, no certification body can check their correctness anyway.

**Comment by otto-ifak** [comment]
@sebbader-sap Thanks for the clarification, we implemented it accordingly in the Test Engines.
From my side, this issue can be closed.
